### ISSUE TITLE
Error building  pynac with clang

### ISSUE THREAD

**Issue by slacka** [pynac/pynac#204] opened 2016-10-12 22:44 UTC
Building with clang results in:

`lst.cpp:29:38: error: explicit specialization of 'tinfo_static' after instantiation 	`

The full log can be found here:
http://clang.debian.net/logs/2016-08-30/pynac_0.6.8-1_unstable_clang.log

**Comment by rwst** [comment] 2016-10-13 14:02
Duplicate of #193
Fixed in pynac-0.6.91 (will probably come with sage-7.5beta0 or so).

**Closed by rwst** 2016-10-13 14:02 UTC
Labels: duplicate
